### ISSUE TITLE
mozc doesn't build with gcc-4.6.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#102]
```
What steps will reproduce the problem?
1. Use gcc-4.6.0 with ChromeOS using the repro instructions here: 
http://code.google.com/p/chromium-os/issues/detail?id=16051&q=gcc-4.6.0&sort=-id
&colspec=ID%20Stars%20Pri%20Area%20Type%20Status%20Summary%20Modified%20Owner%20
Mstone
2.
3.

What is the expected output? What do you see instead?

ibus-mozc-1.1.773.102-r4:   CXX(target) 
out_linux/Release/obj.target/rewriter/rewriter/usage_rewriter.o
ibus-mozc-1.1.773.102-r4: In file included from rewriter/usage_rewriter.cc:40:0:
ibus-mozc-1.1.773.102-r4: 
out_linux/Release/obj/gen/rewriter/usage_rewriter_data.h:1769:1: error: 
converting to non-pointer type ‘int’ from NULL [-Werror=conversion-null]
ibus-mozc-1.1.773.102-r4: 
out_linux/Release/obj/gen/rewriter/usage_rewriter_data.h:1769:1: error: 
converting to non-pointer type ‘int’ from NULL [-Werror=conversion-null]
ibus-mozc-1.1.773.102-r4: cc1plus: all warnings being treated as errors
ibus-mozc-1.1.773.102-r4: 
ibus-mozc-1.1.773.102-r4: make: *** 
[out_linux/Release/obj.target/rewriter/rewriter/usage_rewriter.o] Error 1
ibus-mozc-1.1.773.102-r4: make: *** Waiting for unfinished jobs....
ibus-mozc-1.1.773.102-r4: emake failed
ibus-mozc-1.1.773.102-r4: Traceback (most recent call last):
ibus-mozc-1.1.773.102-r4:   File "build_mozc.py", line 916, in <module>
ibus-mozc-1.1.773.102-r4:     main()
ibus-mozc-1.1.773.102-r4:   File "build_mozc.py", line 902, in main
ibus-mozc-1.1.773.102-r4:     BuildMain(original_directory_name)
ibus-mozc-1.1.773.102-r4:   File "build_mozc.py", line 847, in BuildMain
ibus-mozc-1.1.773.102-r4:     BuildOnLinux(options, targets)
ibus-mozc-1.1.773.102-r4:   File "build_mozc.py", line 762, in BuildOnLinux
ibus-mozc-1.1.773.102-r4:     RunOrDie([make_command] + build_args + 
target_names)
ibus-mozc-1.1.773.102-r4:   File "build_mozc.py", line 567, in RunOrDie
ibus-mozc-1.1.773.102-r4:     '==========']))
ibus-mozc-1.1.773.102-r4: __main__.RunOrDieError: 
ibus-mozc-1.1.773.102-r4: ==========
ibus-mozc-1.1.773.102-r4:  ERROR: emake -j4 MAKE_JOBS=4 BUILDTYPE=Release 
ibus_mozc
ibus-mozc-1.1.773.102-r4: ==========
ibus-mozc-1.1.773.102-r4:  * ERROR: app-i18n/ibus-mozc-1.1.773.102-r4 failed 
(compile phase):
ibus-mozc-1.1.773.102-r4:  *   (no error message)
ibus-mozc-1.1.773.102-r4:  * 
ibus-mozc-1.1.773.102-r4:  * Call stack:
ibus-mozc-1.1.773.102-r4:  *     ebuild.sh, line  56:  Called src_compile
ibus-mozc-1.1.773.102-r4:  *   environment, line 4289:  Called die
ibus-mozc-1.1.773.102-r4:  * The specific snippet of code:
ibus-mozc-1.1.773.102-r4:  *       $(PYTHON) build_mozc.py build 
unix/ibus/ibus.gyp:ibus_mozc -c ${BUILDTYPE} || die
ibus-mozc-1.1.773.102-r4:  * 
ibus-mozc-1.1.773.102-r4:  * If you need support, post the output of 'emerge 
--info =app-i18n/ibus-mozc-1.1.773.102-r4',
ibus-mozc-1.1.773.102-r4:  * the complete build log and the output of 'emerge 
-pqv =app-i18n/ibus-mozc-1.1.773.102-r4'.
ibus-mozc-1.1.773.102-r4:  * This ebuild is from an overlay named 'chromiumos': 
'/home/chrome-bot/trunk/src/third_party/chromiumos-overlay/'
ibus-mozc-1.1.773.102-r4:  * The complete build log is located at 
'/build/x86-generic/tmp/portage/app-i18n/ibus-mozc-1.1.773.102-r4/temp/build.log
'.
ibus-mozc-1.1.773.102-r4:  * The ebuild environment file is located at 
'/build/x86-generic/tmp/portage/app-i18n/ibus-mozc-1.1.773.102-r4/temp/environme
nt'.
ibus-mozc-1.1.773.102-r4:  * S: 
'/build/x86-generic/tmp/portage/app-i18n/ibus-mozc-1.1.773.102-r4/work/ibus-mozc
-1.1.773.102'
ibus-mozc-1.1.773.102-r4: >>> Failed to emerge 
app-i18n/ibus-mozc-1.1.773.102-r4 for /build/x86-generic/, Log file:
ibus-mozc-1.1.773.102-r4: >>>  
'/build/x86-generic/tmp/portage/app-i18n/ibus-mozc-1.1.773.102-r4/temp/build.log
'

What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `asha...@chromium.org` on 25 Aug 2011 at 5:59
