### ISSUE TITLE
MOZC build fail on MacOS Monterey  at mac_util.mm 

### ISSUE THREAD

**Issue by sumiremx5** [google/mozc#537]
I have tried to build MOZC for macOS Monterey (Intel Mac), and build was failed.
I supposed I followed instruction. Would you give me your advice to resolve it ?

%sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

% xcrun -sdk macosx --show-sdk-version
12.1

My instruction was below
1. mkdir -p work
2. cd work
3. python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput
4. cd mozc/src
5. GYP_DEFINES="mac_sdk=12.1 mac_deployment_target=12.1" python3 build_mozc.py gyp --noqt
6. python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput

then during 6. 
Many Warning and Error are reported when process for obj/base/base.mac_util.o
Would you please take a look as below and attached log.

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/SharedFileList.framework/Headers/LSSharedFileList.h:680:1: note: 'LSSharedFileListInsertItemURL' has been explicitly marked deprecated here
LSSharedFileListInsertItemURL(
^
../../base/mac_util.mm:337:9: error: no member named 'CGWindowListCopyWindowInfo' in the global namespace
      ::CGWindowListCopyWindowInfo(
      ~~^
../../base/mac_util.mm:338:11: error: use of undeclared identifier 'kCGWindowListOptionOnScreenOnly'
          kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements,
          ^
../../base/mac_util.mm:338:45: error: use of undeclared identifier 'kCGWindowListExcludeDesktopElements'
          kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements,
                                            ^
../../base/mac_util.mm:339:11: error: use of undeclared identifier 'kCGNullWindowID'
          kCGNullWindowID));
          ^
../../base/mac_util.mm:344:40: error: use of undeclared identifier 'kCGWindowSharingState'
    if ([[window_data objectForKey:(id)kCGWindowSharingState] intValue] ==
                                       ^
../../base/mac_util.mm:345:9: error: use of undeclared identifier 'kCGWindowSharingNone'
        kCGWindowSharingNone) {
        ^
../../base/mac_util.mm:349:59: error: use of undeclared identifier 'kCGWindowName'
    NSString *window_name = [window_data objectForKey:(id)kCGWindowName];
                                                          ^
../../base/mac_util.mm:351:37: error: use of undeclared identifier 'kCGWindowOwnerName'
      [window_data objectForKey:(id)kCGWindowOwnerName];
                                    ^
../../base/mac_util.mm:352:60: error: use of undeclared identifier 'kCGWindowLayer'
    NSNumber *window_layer = [window_data objectForKey:(id)kCGWindowLayer];
                                                           ^
../../base/mac_util.mm:358:36: error: use of undeclared identifier 'kCGNormalWindowLevel'
    if ([window_layer intValue] != kCGNormalWindowLevel) {
                                   ^
27 warnings and 10 errors generated.
`
[build_fail_mac_util_mm.log](https://github.com/google/mozc/files/7845772/build_fail_mac_util_mm.log)

**Comment by sumiremx5** [comment]
Hi hiroyuki-komatsu

Thank you very much for your support. 
It seems `SDK 12.1` makes this issue, and `SDK 10.15` can build MOZC with 1 warning.

> 1. whether CoreGraphics.framework has the definition of CGWindowListCopyWindowInfo.

Both `grep` results are same, but build results are different

```{.scroll}
% grep -rn CGWindowListCopyWindowInfo  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics.tbd:1168:                       _CGWindowLevelForKey, _CGWindowListCopyWindowInfo, _CGWindowListCreate, 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Headers/CGWindow.h:170:CG_EXTERN CFArrayRef __nullable CGWindowListCopyWindowInfo(CGWindowListOption option,
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/MacWindows.h:2164: *      or CGWindowListCopyWindowInfo.


% grep -rn CGWindowListCopyWindowInfo  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics.tbd:1115:                       _CGWindowLevelForKey, _CGWindowListCopyWindowInfo, _CGWindowListCreate, 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Headers/CGWindow.h:170:CG_EXTERN CFArrayRef __nullable CGWindowListCopyWindowInfo(CGWindowListOption option,
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/MacWindows.h:2164: *      or CGWindowListCopyWindowInfo.
```

I'm not sure it is affected for issue. but one observation is file owner for `SDK 12.1` and `SDK 10.15`
```{.scroll}
% cd  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
% pwd
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
 % xcrun -sdk macosx --show-sdk-version                                                                                                                  
12.1
% ls -al
total 0
drwxr-xr-x  5 root  wheel  160  1 12 23:55 .
drwxr-xr-x  6 root  wheel  192 12 15 07:33 ..
drwxr-xr-x  7 root  wheel  224 11 20 07:25 MacOSX.sdk
drwxr-xr-x  9 1000  1000   288  1 12 23:55 MacOSX10.15.sdk
lrwxr-xr-x  1 root  wheel   10  1 10 06:50 MacOSX12.1.sdk -> MacOSX.sdk
```

> 2. whether other SDK versions (i.e. 10.15.6) works on your environment.

`SDK 10.15` can make build with 1 warning. ==> OK

```{.scroll}
sumire@qui src % python3 build_mozc.py clean
sumire@qui src % GYP_DEFINES="mac_sdk=10.15 mac_deployment_target=10.9" python3 build_mozc.py gyp --noqt
INFO: Generating version definition file...
INFO: Version string is 2.26.4610.101
INFO: Running: /usr/local/bin/python3 /Users/sumire/work/mozc/src/build_tools/ensure_gyp_module_path.py --expected=/Users/sumire/work/mozc/src/third_party/gyp/pylib/gyp
INFO: Building GYP command line...
INFO: Running GYP...
INFO: Running: /usr/local/bin/python3 /Users/sumire/work/mozc/src/third_party/gyp/gyp_main.py --depth=. --include=./gyp/common.gypi -D abs_depth=/Users/sumire/work/mozc/src -D ext_third_party_dir=/Users/sumire/work/mozc/src/third_party -D python=/usr/local/bin/python3 ./base/absl.gyp ./base/base.gyp ./base/base_test.gyp ./client/client.gyp ./client/client_test.gyp ./composer/composer.gyp ./composer/composer_test.gyp ./config/config.gyp ./config/config_test.gyp ./converter/converter.gyp ./converter/converter_base.gyp ./converter/converter_main.gyp ./converter/converter_test.gyp ./data/test/session/scenario/scenario.gyp ./data/test/session/scenario/usage_stats/usage_stats.gyp ./data_manager/data_manager.gyp ./data_manager/data_manager_base.gyp ./data_manager/data_manager_test.gyp ./data_manager/oss/oss_data_manager.gyp ./data_manager/oss/oss_data_manager_base.gyp ./data_manager/oss/oss_data_manager_test.gyp ./data_manager/testing/mock_data_manager.gyp ./data_manager/testing/mock_data_manager_base.gyp ./data_manager/testing/mock_data_manager_test.gyp ./dictionary/dictionary.gyp ./dictionary/dictionary_base.gyp ./dictionary/dictionary_test.gyp ./dictionary/file/dictionary_file.gyp ./dictionary/file/dictionary_file_test.gyp ./dictionary/system/system_dictionary.gyp ./dictionary/system/system_dictionary_test.gyp ./engine/engine.gyp ./engine/engine_test.gyp ./gui/gui.gyp ./gyp/tests.gyp ./ios/ios.gyp ./ipc/ipc.gyp ./mac/mac.gyp ./net/jsoncpp.gyp ./net/net.gyp ./net/net_test.gyp ./prediction/prediction.gyp ./prediction/prediction_base.gyp ./prediction/prediction_test.gyp ./protobuf/protobuf.gyp ./protocol/protocol.gyp ./renderer/renderer.gyp ./request/request.gyp ./rewriter/calculator/calculator.gyp ./rewriter/rewriter.gyp ./rewriter/rewriter_base.gyp ./rewriter/rewriter_test.gyp ./server/server.gyp ./session/session.gyp ./session/session_base.gyp ./session/session_test.gyp ./storage/storage.gyp ./storage/storage_test.gyp ./testing/testing.gyp ./transliteration/transliteration.gyp ./transliteration/transliteration_test.gyp ./usage_stats/usage_stats_base.gyp ./usage_stats/usage_stats_test.gyp -D version=2.26.4610.101 -D short_version=2.26.4610 -D branding=Mozc -D use_qt=NO -D qt_dir= -D use_wix=NO -D build_base=/Users/sumire/work/mozc/src/out_mac -D build_short_base=out_mac -D warn_as_error=0 -D channel_dev=1 -D target_platform=Mac --generator-output=. -G output_dir=out_mac
INFO: Done
sumire@qui src % python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput
INFO: Running: ninja -C out_mac/Release GoogleJapaneseInput
ninja: Entering directory `out_mac/Release'
[516/986] ACTION breakpad: build_breakpad_d1a7ebf554c28b7acfa2ad7d1e06d7b2
Done: rsync -avH /Users/sumire/work/mozc/src/third_party/breakpad/src/ /Users/sumire/work/mozc/src/out_mac/Release/Breakpad/src
Done: xcodebuild -project /Users/sumire/work/mozc/src/out_mac/Release/Breakpad/src/client/mac/Breakpad.xcodeproj -configuration Release -target Breakpad -arch x86_64 -sdk macosx10.15 GCC_VERSION=com.apple.compilers.llvm.clang.1_0 MACOSX_DEPLOYMENT_TARGET=10.9 CONFIGURATION_BUILD_DIR=/Users/sumire/work/mozc/src/out_mac/Release/Breakpad OTHER_CFLAGS=-Wno-switch
Done: xcodebuild -project /Users/sumire/work/mozc/src/out_mac/Release/Breakpad/src/tools/mac/dump_syms/dump_syms.xcodeproj -configuration Release -target dump_syms -arch x86_64 -sdk macosx10.15 GCC_VERSION=com.apple.compilers.llvm.clang.1_0 MACOSX_DEPLOYMENT_TARGET=10.9 CONFIGURATION_BUILD_DIR=/Users/sumire/work/mozc/src/out_mac/Release/Breakpad OTHER_CFLAGS=-Wno-switch
Done: xcodebuild -project /Users/sumire/work/mozc/src/out_mac/Release/Breakpad/src/tools/mac/symupload/symupload.xcodeproj -configuration Release -target symupload -arch x86_64 -sdk macosx10.15 GCC_VERSION=com.apple.compilers.llvm.clang.1_0 MACOSX_DEPLOYMENT_TARGET=10.9 CONFIGURATION_BUILD_DIR=/Users/sumire/work/mozc/src/out_mac/Release/Breakpad OTHER_CFLAGS=-Wno-switch
[922/986] OBJCXX obj/renderer/mac/mozc_renderer.CandidateView.o
../../renderer/mac/CandidateView.mm:73:18: warning: 'setFlipped:' is deprecated: first deprecated in macOS 10.6 - The concept of flippedness for NSImage is deprecated.  Please see the AppKit 10.6 release notes for a discussion of why and for how to replace existing usage. [-Wdeprecated-declarations]
    [g_LogoImage setFlipped:YES];
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSImage.h:244:1: note: 'setFlipped:' has been explicitly marked deprecated here
- (void)setFlipped:(BOOL)flag API_DEPRECATED("The concept of flippedness for NSImage is deprecated.  Please see the AppKit 10.6 release notes for a discussion of why and for how to replace existing usage.", macos(10.0,10.6));
^
1 warning generated.
[984/986] OBJCXX obj/mac/GoogleJapaneseInput.GoogleJapaneseInputController.o
../../mac/GoogleJapaneseInputController.mm:206:13: warning: 'loadNibNamed:owner:' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
  [NSBundle loadNibNamed:@"Config" owner:self];
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSNibLoading.h:32:1: note: 'loadNibNamed:owner:' has been explicitly marked deprecated here
+ (BOOL)loadNibNamed:(null_unspecified NSString *)nibName owner:(null_unspecified id)owner API_DEPRECATED("", macos(10.0,10.8));
^
1 warning generated.
[986/986] STAMP Mozc.app
```

Just in case, I build SDK 12.1 with `Mac_deployment_target=10.9` instead of `Mac_deployment_target=12.1`, but error was reported ==> Build fail

```{.scroll}
sumire@qui src % python3 build_mozc.py clean
sumire@qui src % GYP_DEFINES="mac_sdk=12.1 mac_deployment_target=10.9" python3 build_mozc.py gyp --noqt 
INFO: Generating version definition file...
INFO: Version string is 2.26.4610.101
INFO: Running: /usr/local/bin/python3 /Users/sumire/work/mozc/src/build_tools/ensure_gyp_module_path.py --expected=/Users/sumire/work/mozc/src/third_party/gyp/pylib/gyp
INFO: Building GYP command line...
INFO: Running GYP...
INFO: Running: /usr/local/bin/python3 /Users/sumire/work/mozc/src/third_party/gyp/gyp_main.py --depth=. --include=./gyp/common.gypi -D abs_depth=/Users/sumire/work/mozc/src -D ext_third_party_dir=/Users/sumire/work/mozc/src/third_party -D python=/usr/local/bin/python3 ./base/absl.gyp ./base/base.gyp ./base/base_test.gyp ./client/client.gyp ./client/client_test.gyp ./composer/composer.gyp ./composer/composer_test.gyp ./config/config.gyp ./config/config_test.gyp ./converter/converter.gyp ./converter/converter_base.gyp ./converter/converter_main.gyp ./converter/converter_test.gyp ./data/test/session/scenario/scenario.gyp ./data/test/session/scenario/usage_stats/usage_stats.gyp ./data_manager/data_manager.gyp ./data_manager/data_manager_base.gyp ./data_manager/data_manager_test.gyp ./data_manager/oss/oss_data_manager.gyp ./data_manager/oss/oss_data_manager_base.gyp ./data_manager/oss/oss_data_manager_test.gyp ./data_manager/testing/mock_data_manager.gyp ./data_manager/testing/mock_data_manager_base.gyp ./data_manager/testing/mock_data_manager_test.gyp ./dictionary/dictionary.gyp ./dictionary/dictionary_base.gyp ./dictionary/dictionary_test.gyp ./dictionary/file/dictionary_file.gyp ./dictionary/file/dictionary_file_test.gyp ./dictionary/system/system_dictionary.gyp ./dictionary/system/system_dictionary_test.gyp ./engine/engine.gyp ./engine/engine_test.gyp ./gui/gui.gyp ./gyp/tests.gyp ./ios/ios.gyp ./ipc/ipc.gyp ./mac/mac.gyp ./net/jsoncpp.gyp ./net/net.gyp ./net/net_test.gyp ./prediction/prediction.gyp ./prediction/prediction_base.gyp ./prediction/prediction_test.gyp ./protobuf/protobuf.gyp ./protocol/protocol.gyp ./renderer/renderer.gyp ./request/request.gyp ./rewriter/calculator/calculator.gyp ./rewriter/rewriter.gyp ./rewriter/rewriter_base.gyp ./rewriter/rewriter_test.gyp ./server/server.gyp ./session/session.gyp ./session/session_base.gyp ./session/session_test.gyp ./storage/storage.gyp ./storage/storage_test.gyp ./testing/testing.gyp ./transliteration/transliteration.gyp ./transliteration/transliteration_test.gyp ./usage_stats/usage_stats_base.gyp ./usage_stats/usage_stats_test.gyp -D version=2.26.4610.101 -D short_version=2.26.4610 -D branding=Mozc -D use_qt=NO -D qt_dir= -D use_wix=NO -D build_base=/Users/sumire/work/mozc/src/out_mac -D build_short_base=out_mac -D warn_as_error=0 -D channel_dev=1 -D target_platform=Mac --generator-output=. -G output_dir=out_mac
INFO: Done
sumire@qui src % python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput                
INFO: Running: ninja -C out_mac/Release GoogleJapaneseInput
ninja: Entering directory `out_mac/Release'
[133/986] OBJCXX obj.host/base/base.mac_util.o
FAILED: obj.host/base/base.mac_util.o 
c++ -MMD -MF obj.host/base/base.mac_util.o.d -D__APPLE__ -DMOZC_BUILD -DCHANNEL_DEV -DNDEBUG -DQT_NO_DEBUG -DMOZC_NO_LOGGING -DIGNORE_HELP_FLAG -DIGNORE_INVALID_FLAG -I/Users/sumire/work/mozc/src -Igen -I../../third_party/abseil-cpp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -fasm-blocks -mpascal-strings -O2 -gdwarf-2 -mmacosx-version-min=10.9 -arch x86_64 -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unnamed-type-template-args -std=c++17 -stdlib=libc++ -fno-exceptions -fvisibility-inlines-hidden -fmessage-length=0 -fno-strict-aliasing -funsigned-char -pipe -pthread -fno-omit-frame-pointer -fstack-protector -fobjc-arc -O2  -c ../../base/mac_util.mm -o obj.host/base/base.mac_util.o
../../base/mac_util.mm:337:9: error: no member named 'CGWindowListCopyWindowInfo' in the global namespace
      ::CGWindowListCopyWindowInfo(
      ~~^
../../base/mac_util.mm:338:11: error: use of undeclared identifier 'kCGWindowListOptionOnScreenOnly'
          kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements,
          ^
../../base/mac_util.mm:338:45: error: use of undeclared identifier 'kCGWindowListExcludeDesktopElements'
          kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements,
                                            ^
../../base/mac_util.mm:339:11: error: use of undeclared identifier 'kCGNullWindowID'
          kCGNullWindowID));
          ^
../../base/mac_util.mm:344:40: error: use of undeclared identifier 'kCGWindowSharingState'
    if ([[window_data objectForKey:(id)kCGWindowSharingState] intValue] ==
                                       ^
../../base/mac_util.mm:345:9: error: use of undeclared identifier 'kCGWindowSharingNone'
        kCGWindowSharingNone) {
        ^
../../base/mac_util.mm:349:59: error: use of undeclared identifier 'kCGWindowName'
    NSString *window_name = [window_data objectForKey:(id)kCGWindowName];
                                                          ^
../../base/mac_util.mm:351:37: error: use of undeclared identifier 'kCGWindowOwnerName'
      [window_data objectForKey:(id)kCGWindowOwnerName];
                                    ^
../../base/mac_util.mm:352:60: error: use of undeclared identifier 'kCGWindowLayer'
    NSNumber *window_layer = [window_data objectForKey:(id)kCGWindowLayer];
                                                           ^
../../base/mac_util.mm:358:36: error: use of undeclared identifier 'kCGNormalWindowLevel'
    if ([window_layer intValue] != kCGNormalWindowLevel) {
                                   ^
10 errors generated.
[142/986] CXX obj.host/data_manager/serialized_dictionary.serialized_dictionary.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users/sumire/work/mozc/src/build_mozc.py", line 887, in <module>
    sys.exit(main())
  File "/Users/sumire/work/mozc/src/build_mozc.py", line 872, in main
    BuildMain(cmd_opts, cmd_args)
  File "/Users/sumire/work/mozc/src/build_mozc.py", line 612, in BuildMain
    BuildWithNinja(options, targets)
  File "/Users/sumire/work/mozc/src/build_mozc.py", line 586, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg, target_name])
  File "/Users/sumire/work/mozc/src/build_tools/util.py", line 96, in RunOrDie
    raise RunOrDieError('\n'.join(['',
build_tools.util.RunOrDieError: 
==========
 ERROR: ninja -C out_mac/Release GoogleJapaneseInput
==========
```

Again, Thank you very much for your comment and support. I'll confirm whether `SDK 10.15` works well.

**Comment by sumiremx5** [comment]
Thank you very much for your support. 

I quickly checked. MOZC (Build with SDK 10.15) works on my Mac

- MacBook Pro (Retina, 15-inch, Mid 2015)
- Monterey

and also, I build for "mozc_emacs_helper" with small modification for build_mozc.py. and works well.

**Comment by hiroyuki-komatsu** [comment]
I'm glad to hear that you can build Mozc on your machine.
I was also able to build Mozc with Xcode 13.1 (SDK 12.0).

I'm going to move this topic from issue to discussion.
Thanks,
